HW3: Task 3
ValeriL/Epam_Python pull request #15
Opened 2020-11-18 23:15 UTC by ValeriL

2020-11-19 17:26 UTC, ValeriL commented
Well, Ive already understood my mistakes here after this lecture

2020-11-19 20:22 UTC, Cjkjvfnby commented
> Well, Ive already understood my mistakes here after this lecture

Have you fixed them?

2020-11-20 18:49 UTC, Cjkjvfnby requested changes

2020-11-20 18:49 UTC, Cjkjvfnby commented on Homework/homework3/test_task3.py
> +def test_make_filter_faulty_tests(filter_data, expected_result: List[Any]):
What do `faulty_tests` mean?

2020-11-22 21:33 UTC, Cjkjvfnby approved these changes

2020-11-22 22:17 UTC, merged